services:
  - type: web
    name: fragrance-api
    runtime: docker
    plan: free
    rootDir: backend/FragranceCommerce.Api
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: hostBuilder__reloadConfigOnChange
        value: "false"
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Jwt__Key
        sync: false
      - key: Jwt__Issuer
        sync: false
      - key: Jwt__Audience
        sync: false
      - key: CloudinarySettings__CloudName
        sync: false
      - key: CloudinarySettings__ApiKey
        sync: false
      - key: CloudinarySettings__ApiSecret
        sync: false
      - key: CORS__AllowedOrigins
        sync: false
